name: Build LF-Launcher

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4

    - name: Instalar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permiso al script
      run: chmod +x ./gradlew
      shell: bash

    - name: Compilar con Gradle
      run: ./gradlew shadowJar
      shell: bash

    - name: Preparar carpeta de salida
      run: mkdir -p build/distributions

    - name: Empaquetar en EXE
      uses: actions/upload-artifact@v4
      with:
        name: LF-Launcher
        path: build/libs/*.jar
